from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BLOGS = ROOT / "blogs"
NOTEBOOKS = ROOT / "notebooks"
BRANCH = "feature/02-class8-to-phd-learning"


def numbered(path):
    m = re.match(r"(\d+)-", path.name)
    return int(m.group(1)) if m else 10_000


def title_from_markdown(text, fallback):
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def main():
    blogs = sorted(BLOGS.glob("*.md"), key=numbered)
    notebooks = sorted(NOTEBOOKS.glob("*.ipynb"), key=numbered)
    notebook_by_num = {numbered(p): p for p in notebooks}
    rows, missing, review = [], [], []

    for blog in blogs:
        n = numbered(blog)
        text = blog.read_text(encoding="utf-8")
        title = title_from_markdown(text, blog.stem)
        nb = notebook_by_num.get(n)
        if not nb:
            missing.append(f"{n:02d} {blog.name}")
        checks = [
            bool(re.search(r"objective|goal|learn", text, re.I)),
            bool(re.search(r"derivative|equation|matrix|vector|loss|gradient|probability", text, re.I)),
            bool(re.search(r"next|where.*go|continue", text, re.I)),
        ]
        if sum(checks) < 2:
            review.append(f"{n:02d} {blog.name}")
        nb_link = f"[Open notebook](notebooks/{nb.name})" if nb else "—"
        colab = f"https://colab.research.google.com/github/manish7725/deeplearning/blob/{BRANCH}/notebooks/{nb.name}" if nb else "—"
        colab_link = f"[Open in Colab]({colab})" if nb else "—"
        rows.append(f"| {n:02d} | [{title}](blogs/{blog.name}) | {nb_link} | {colab_link} |")

    report = "# Learning Map\n\n> Generated by repository automation. Blog = textbook; notebook = laboratory.\n\n## Lesson map\n\n| # | Blog | Notebook | Colab |\n|---:|---|---|---|\n" + "\n".join(rows) + "\n\n## Audit\n\n"
    report += f"- Blogs: **{len(blogs)}**\n- Notebooks: **{len(notebooks)}**\n- Missing notebook matches: **{len(missing)}**\n- Content-review queue: **{len(review)}**\n"
    if missing:
        report += "\n### Missing notebook matches\n\n" + "\n".join(f"- {x}" for x in missing) + "\n"
    if review:
        report += "\n### Content-review queue\n\n" + "\n".join(f"- {x}" for x in review) + "\n"
    report += "\n## Learning contract\n\nStory → intuition → numerical example → mathematics → hand calculation → NumPy → PyTorch → visualization → experiment → failure mode → project → paper → research question.\n"
    (ROOT / "LEARNING_MAP.md").write_text(report, encoding="utf-8")
    (ROOT / "learning_audit.txt").write_text(
        f"blogs={len(blogs)}\nnotebooks={len(notebooks)}\nmissing_notebooks={len(missing)}\ncontent_review_queue={len(review)}\n",
        encoding="utf-8",
    )
    print(report)


if __name__ == "__main__":
    main()
