import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BLOGS, NOTEBOOKS = ROOT / 'blogs', ROOT / 'notebooks'

# Every recipe is a small computational reconstruction of the lesson's central idea.
# The Markdown blog remains authoritative; this file only supplies executable companions.
RECIPES = {
'01': ('Learning loop: y=2x+1', '''import numpy as np\nx=np.array([1.,2.,3.]); y=np.array([3.,5.,7.])\nw,b=0.,0.\nyhat=w*x+b; loss=((yhat-y)**2).mean()\nprint("predictions:", yhat, "loss:", loss)\ngw=(2*(yhat-y)*x).mean(); gb=(2*(yhat-y)).mean()\nprint("gradients:", gw, gb)''', '''import torch\nx=torch.tensor([1.,2.,3.]); y=torch.tensor([3.,5.,7.])\nw=torch.tensor(0.,requires_grad=True); b=torch.tensor(0.,requires_grad=True)\nloss=((w*x+b-y)**2).mean(); loss.backward()\nprint(loss.item(), w.grad.item(), b.grad.item())''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.linspace(0,3,50); plt.plot(x,2*x+1,label="target")\nplt.scatter([1,2,3],[3,5,7],label="data"); plt.xlabel("x"); plt.ylabel("y"); plt.title("Learning from examples"); plt.legend(); plt.show()''', '''# Change exactly one variable: the learning rate\nfor eta in [.01,.1,.5]:\n    w,b=0.,0.\n    for _ in range(50):\n        e=w*x+b-y; w-=eta*(2*e*x).mean(); b-=eta*(2*e).mean()\n    print(eta,w,b)''', '''# Intentional failure: update in the wrong direction\nw,b=0.,0.; eta=.1\nfor _ in range(5):\n    e=w*x+b-y; w+=eta*(2*e*x).mean(); b+=eta*(2*e).mean()\nprint("wrong-direction loss:",((w*x+b-y)**2).mean())'''),
'02': ('Vector geometry: length, dot product, distance', '''import numpy as np\nu=np.array([3.,4.]); v=np.array([4.,-3.])\nprint("||u||=",np.linalg.norm(u)); print("u·v=",u@v); print("distance=",np.linalg.norm(u-v))''', '''import torch\nu=torch.tensor([3.,4.]); v=torch.tensor([4.,-3.])\nprint(torch.linalg.vector_norm(u),u@v,torch.linalg.vector_norm(u-v))''', '''import numpy as np, matplotlib.pyplot as plt\nu=np.array([3.,4.]); v=np.array([4.,-3.]); plt.quiver([0,0],[0,0],[u[0],v[0]],[u[1],v[1]],angles='xy',scale_units='xy',scale=1); plt.xlim(-1,6); plt.ylim(-5,6); plt.axhline(0); plt.axvline(0); plt.title("Two vectors"); plt.show()''', '''v2=2*v; print("original length",np.linalg.norm(v),"new length",np.linalg.norm(v2))''', '''# Failure: treating a dot product as a distance\nprint("dot product (not a distance):",u@v)'''),
'03': ('Matrix multiplication: y=Wx', '''import numpy as np\nW=np.array([[1.,2.],[3.,4.]]); x=np.array([5.,6.])\nprint("row 1 dot x:",W[0]@x); print("row 2 dot x:",W[1]@x); print("Wx:",W@x)''', '''import torch\nW=torch.tensor([[1.,2.],[3.,4.]]); x=torch.tensor([5.,6.]); print(W@x)''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.array([5.,6.]); y=np.array([[1,2],[3,4]])@x; plt.bar(["row 1","row 2"],y); plt.ylabel("output"); plt.title("Each row is a dot product"); plt.show()''', '''W2=W.copy(); W2[0,0]+=1; print("only W[0,0] changed:",W2@x)''', '''# Failure: reverse the multiplication order when shapes do not agree\ntry: print(x@W)\nexcept ValueError as e: print("shape failure:",e)'''),
'04': ('Linear transformation: T(x)=Ax', '''import numpy as np\nA=np.array([[0.,-1.],[1.,0.]])\nP=np.array([[1.,0.],[0.,1.],[-1.,0.],[0.,-1.]])\nprint("before:\n",P); print("after:\n",P@A.T)''', '''import torch\nA=torch.tensor([[0.,-1.],[1.,0.]]); P=torch.tensor([[1.,0.],[0.,1.],[-1.,0.],[0.,-1.]])\nprint(P@A.T)''', '''import numpy as np, matplotlib.pyplot as plt\nA=np.array([[0.,-1.],[1.,0.]]); P=np.array([[1.,0.],[0.,1.],[-1.,0.],[0.,-1.]])\nQ=P@A.T; plt.plot(*np.vstack([P,P[0]]).T,label="before"); plt.plot(*np.vstack([Q,Q[0]]).T,label="after"); plt.axis('equal'); plt.legend(); plt.title("A matrix moves points"); plt.show()''', '''A2=A.copy(); A2[0,0]=1; print("changed one matrix entry:\n",P@A2.T)''', '''# Failure: applying A elementwise instead of as a transformation\nprint("elementwise result:\n",P*A)'''),
'05': ('One neuron: z=w·x+b', '''import numpy as np\nx=np.array([2.,3.]); w=np.array([.5,-1.]); b=2.\nproducts=w*x; z=products.sum()+b\nprint("products",products,"sum",products.sum(),"z",z)''', '''import torch\nx=torch.tensor([2.,3.]); w=torch.tensor([.5,-1.]); b=torch.tensor(2.)\nprint(w@x+b)''', '''import numpy as np, matplotlib.pyplot as plt\nw=np.linspace(-2,2,80); z=w*2 + (-1)*3 + 2; plt.plot(w,z); plt.axhline(0); plt.xlabel("first weight"); plt.ylabel("z"); plt.title("A neuron is a linear function before activation"); plt.show()''', '''w2=w.copy(); w2[0]+=1; print("only first weight changed:",w2@x+b)''', '''# Failure: forget the bias\nprint("without bias:",w@x,"with bias:",w@x+b)'''),
'06': ('Activation functions: a=f(z)', '''import numpy as np\nz=np.linspace(-4,4,9)\nprint("z",z); print("ReLU",np.maximum(0,z)); print("sigmoid",1/(1+np.exp(-z))); print("tanh",np.tanh(z))''', '''import torch\nz=torch.linspace(-4,4,9); print(torch.relu(z)); print(torch.sigmoid(z)); print(torch.tanh(z))''', '''import numpy as np, matplotlib.pyplot as plt\nz=np.linspace(-5,5,200); plt.plot(z,np.maximum(0,z),label="ReLU"); plt.plot(z,1/(1+np.exp(-z)),label="sigmoid"); plt.plot(z,np.tanh(z),label="tanh"); plt.legend(); plt.axhline(0); plt.title("Same z, different nonlinearities"); plt.show()''', '''z2=z.copy(); z2[4]+=1; print("only z[4] changed:",np.maximum(0,z2)[4])''', '''# Failure: using ReLU when negative outputs are required\nprint("ReLU(-3)=",max(0,-3))'''),
'07': ('Prediction versus loss', '''import numpy as np\ny=5.; predictions=np.arange(0.,11.)\nloss=(predictions-y)**2\nfor p,L in zip(predictions,loss): print(p,L)''', '''import torch\ny=torch.tensor(5.); p=torch.linspace(0,10,11); print((p-y)**2)''', '''import numpy as np, matplotlib.pyplot as plt\np=np.linspace(0,10,200); plt.plot(p,(p-5)**2); plt.axvline(5,linestyle='--'); plt.xlabel("prediction"); plt.ylabel("squared error"); plt.title("A loss gives feedback"); plt.show()''', '''y2=6.; print("only target changed; loss at p=5:",(5-y2)**2)''', '''# Failure: report prediction alone without a score\nprint("prediction=5 is meaningful only relative to a target")'''),
'08': ('Derivative as local slope', '''import numpy as np\nf=lambda w:(w-3)**2; w=1.; h=1e-5\nanalytical=2*(w-3); finite=(f(w+h)-f(w-h))/(2*h)\nprint("analytical",analytical,"finite difference",finite)''', '''import torch\nw=torch.tensor(1.,requires_grad=True); f=(w-3)**2; f.backward(); print("autograd",w.grad.item())''', '''import numpy as np, matplotlib.pyplot as plt\nw=np.linspace(-1,6,200); plt.plot(w,(w-3)**2); plt.scatter([1],[(1-3)**2]); plt.xlabel("w"); plt.ylabel("f(w)"); plt.title("Slope changes along the curve"); plt.show()''', '''h2=1e-2; print("changing only finite-difference step:",(f(w+h2)-f(w-h2))/(2*h2))''', '''# Failure: use a one-sided large step and call it the exact derivative\nprint("large-step estimate:",(f(2)-f(1))/(2-1))'''),
'09': ('Gradient descent: w_next=w-eta*2(w-3)', '''import numpy as np\nw=0.; eta=.1\nfor i in range(10):\n    L=(w-3)**2; g=2*(w-3)\n    print(f"step {i}: w={w:.6f}, L={L:.6f}, gradient={g:.6f}")\n    w=w-eta*g''', '''import torch\nw=torch.tensor(0.)\neta=.1\nfor i in range(10):\n    loss=(w-3)**2; g=2*(w-3); w=w-eta*g\n    print(i,w.item(),loss.item())''', '''import numpy as np, matplotlib.pyplot as plt\nwgrid=np.linspace(-1,7,300); plt.plot(wgrid,(wgrid-3)**2,label="L(w)")\nfor eta in [.01,.1,.5,1.1]:\n    w=0.; path=[w]\n    for _ in range(15): w-=eta*2*(w-3); path.append(w)\n    plt.plot(path,[(q-3)**2 for q in path],marker='o',label=f"eta={eta}")\nplt.xlabel("w"); plt.ylabel("loss"); plt.legend(); plt.title("Gradient descent trajectory on the loss landscape"); plt.show()''', '''for eta in [.01,.1,.5,1.1]:\n    w=0.\n    for _ in range(20): w-=eta*2*(w-3)\n    print("eta",eta,"final w",w)''', '''# Failure: too-large learning rate can oscillate/diverge\nw=0.; eta=1.1\nfor i in range(8):\n    w-=eta*2*(w-3); print(i,w,(w-3)**2)'''),
'10': ('Backpropagation via chain rule', '''import numpy as np\nw,x,b,y=2.,3.,1.,7.\nyhat=w*x+b; L=(yhat-y)**2\ndL_dyhat=2*(yhat-y); dyhat_dw=x; dL_dw=dL_dyhat*dyhat_dw\nprint(yhat,L,dL_dyhat,dyhat_dw,dL_dw)''', '''import torch\nw=torch.tensor(2.,requires_grad=True); x=torch.tensor(3.); b=torch.tensor(1.); y=torch.tensor(7.)\nL=(w*x+b-y)**2; L.backward(); print(L.item(),w.grad.item())''', '''import numpy as np, matplotlib.pyplot as plt\nw=np.linspace(0,4,100); plt.plot(w,(w*3+1-7)**2); plt.axvline(2,linestyle='--'); plt.xlabel("w"); plt.ylabel("loss"); plt.title("Backprop gives the slope with respect to w"); plt.show()''', '''x2=4.; print("only input changed; local derivative dyhat/dw=",x2)''', '''# Failure: drop one chain-rule factor\nprint("wrong gradient:",2*(w*x+b-y),"correct:",dL_dw)'''),
'11': ('Tensors and dimensions', '''import numpy as np\nx=np.arange(24.).reshape(2,3,4)\nprint("shape",x.shape); print("mean over last axis shape",x.mean(axis=-1).shape); print(x.mean(axis=-1))''', '''import torch\nx=torch.arange(24.).reshape(2,3,4); print(x.shape,x.mean(-1).shape,x.mean(-1))''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.arange(24.).reshape(2,3,4); plt.imshow(x[0]); plt.colorbar(); plt.title("One 3x4 slice of a tensor"); plt.xlabel("axis 2"); plt.ylabel("axis 1"); plt.show()''', '''x2=x.reshape(2,3,4); x2=x2+1; print("only values changed; shape remains",x2.shape)''', '''# Failure: reshape to an incompatible number of elements\ntry: print(x.reshape(5,5))\nexcept ValueError as e: print("shape failure:",e)'''),
'12': ('Training and testing on unseen data', '''import numpy as np\nx=np.arange(1,6.); y=2*x+1; xt=np.array([6.,8.]); yt=2*xt+1\nprint("train",x,y); print("test",xt,yt); print("test MSE of true rule",np.mean((2*xt+1-yt)**2))''', '''import torch\nx=torch.arange(1.,6.); y=2*x+1; xt=torch.tensor([6.,8.]); yt=2*xt+1\nprint(torch.mean((2*xt+1-yt)**2))''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.arange(1,9.); plt.scatter(x,2*x+1); plt.axvline(5.5,linestyle='--'); plt.text(5.6,2,"train | test"); plt.title("Test points were not used for fitting"); plt.show()''', '''xt2=np.array([7.]); print("only test input changed:",2*xt2+1)''', '''# Failure: accidentally evaluate test labels during training\nprint("Leakage warning: do not fit parameters using test labels")'''),
'13': ('Convolution as a sliding local dot product', '''import numpy as np\nx=np.array([1.,2.,3.,4.,5.]); k=np.array([1.,0.,-1.])\nfor i in range(len(x)-len(k)+1): print(i,x[i:i+3],x[i:i+3]@k)''', '''import torch\nx=torch.tensor([[[[1.,2.,3.,4.,5.]]]])\nk=torch.tensor([[[[1.,0.,-1.]]]])\nprint(torch.nn.functional.conv2d(x,k))''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.array([1.,2.,3.,4.,5.]); k=np.array([1.,0.,-1.]); y=[x[i:i+3]@k for i in range(3)]\nplt.bar(range(3),y); plt.xlabel("window position"); plt.ylabel("response"); plt.title("Kernel response while sliding"); plt.show()''', '''k2=k.copy(); k2[0]=2; print("only first kernel weight changed:",[x[i:i+3]@k2 for i in range(3)])''', '''# Failure: use a kernel longer than the signal\ntry: print([x[i:i+7]@np.ones(7) for i in range(1)])\nexcept ValueError as e: print(e)'''),
'14': ('Sequence recurrence h_t=.5h_(t-1)+x_t', '''def run(xs):\n    h=0.; out=[]\n    for x in xs: h=.5*h+x; out.append(h)\n    return out\nprint("forward",run([1.,2.,3.,4.])); print("reverse",run([4.,3.,2.,1.]))''', '''import torch\ndef run(xs):\n    h=torch.tensor(0.)\n    for x in xs: h=.5*h+x\n    return h\nprint(run([1.,2.,3.,4.]),run([4.,3.,2.,1.]))''', '''import numpy as np, matplotlib.pyplot as plt\nfor xs in ([1,2,3,4],[4,3,2,1]): plt.plot(run(xs),marker='o',label=str(xs))\nplt.xlabel("time step"); plt.ylabel("hidden state"); plt.legend(); plt.title("Order changes the hidden state trajectory"); plt.show()''', '''print("only last element changed:",run([1,2,3,5]))''', '''# Failure: reset the hidden state at every step\nprint([x for x in [1,2,3,4]])'''),
'15': ('Word embeddings and cosine similarity', '''import numpy as np\nu=np.array([1.,.8]); near=np.array([.9,.9]); far=np.array([-1.,.2])\ndef cos(a,b): return a@b/(np.linalg.norm(a)*np.linalg.norm(b))\nprint(cos(u,near),cos(u,far))''', '''import torch\nu=torch.tensor([1.,.8]); a=torch.tensor([.9,.9]); b=torch.tensor([-1.,.2])\nprint(torch.nn.functional.cosine_similarity(u,a,dim=0),torch.nn.functional.cosine_similarity(u,b,dim=0))''', '''import numpy as np, matplotlib.pyplot as plt\nE=np.array([[1,.8],[.9,.9],[-1,.2]]); plt.scatter(E[:,0],E[:,1]);\nfor i,t in enumerate(["u","near","far"]): plt.text(E[i,0],E[i,1],t); plt.axhline(0); plt.axvline(0); plt.axis('equal'); plt.title("Embedding geometry"); plt.show()''', '''near2=np.array([.8,1.]); print("only near vector changed:",cos(u,near2))''', '''# Failure: compare raw dot products when vector lengths differ\nprint("raw dot",u@near,"cosine",cos(u,near))'''),
'16': ('Attention: softmax(QK^T/sqrt(d))V', '''import numpy as np\nQ=np.array([[1.,0.]]); K=np.array([[1.,0.],[0.,1.]]); V=np.array([[10.,0.],[0.,20.]])\ns=Q@K.T; a=np.exp(s-s.max())/np.exp(s-s.max()).sum(); print("scores",s,"weights",a,"output",a@V)''', '''import torch\nQ=torch.tensor([[1.,0.]]); K=torch.tensor([[1.,0.],[0.,1.]]); V=torch.tensor([[10.,0.],[0.,20.]])\na=torch.softmax(Q@K.T,1); print(a,a@V)''', '''import numpy as np, matplotlib.pyplot as plt\na=np.array([.731,.269]); plt.bar(["key 1","key 2"],a); plt.ylim(0,1); plt.ylabel("attention weight"); plt.title("Which values does the query read?"); plt.show()''', '''V2=V.copy(); V2[0,0]=20; print("only one value changed; output:",a@V2)''', '''# Failure: use raw scores as if they were probabilities\nprint("raw scores do not sum to one:",s,s.sum())'''),
'17': ('Transformer block: attention + residual + feed-forward', '''import numpy as np\nX=np.array([[1.,2.],[3.,1.]])\nS=X@X.T; A=np.exp(S-S.max(1,keepdims=True)); A/=A.sum(1,keepdims=True)\natt=A@X; residual=X+att; ffn=np.maximum(0,residual@np.array([[1.,0.],[0.,1.]]))\nprint("attention",A,"residual",residual,"ffn",ffn)''', '''import torch\nX=torch.tensor([[1.,2.],[3.,1.]])\nA=torch.softmax(X@X.T,1); Y=X+A@X; print(A,Y)''', '''import numpy as np, matplotlib.pyplot as plt\nX=np.array([[1.,2.],[3.,1.]]); A=np.exp(X@X.T-(X@X.T).max(1,keepdims=True)); A/=A.sum(1,keepdims=True)\nplt.imshow(A); plt.colorbar(); plt.xticks([0,1],["token 1","token 2"]); plt.yticks([0,1],["token 1","token 2"]); plt.title("Self-attention matrix"); plt.show()''', '''X2=X.copy(); X2[0,0]+=1; print("only one token feature changed:\n",X2@X2.T)''', '''# Failure: omit normalization and call exponentiated scores probabilities\nraw=np.exp(X@X.T); print("row sums without softmax normalization",raw.sum(1))'''),
'18': ('Language model next-token probabilities', '''import numpy as np\nlogits=np.array([2.,1.,0.,-1.]); p=np.exp(logits-logits.max()); p/=p.sum(); print(p,p.sum())''', '''import torch\nlogits=torch.tensor([2.,1.,0.,-1.]); p=torch.softmax(logits,0); print(p,p.sum())''', '''import numpy as np, matplotlib.pyplot as plt\np=np.exp(np.array([2.,1.,0.,-1.])-2); p/=p.sum(); plt.bar(["A","B","C","D"],p); plt.ylabel("probability"); plt.title("Next-token distribution"); plt.show()''', '''logits2=logits.copy(); logits2[0]+=1; print("only top logit changed:",np.exp(logits2-logits2.max())/np.exp(logits2-logits2.max()).sum())''', '''# Failure: use raw logits as probabilities\nprint("raw logits sum:",logits.sum())'''),
'19': ('Generative sampling from a distribution', '''import numpy as np\nrng=np.random.default_rng(0); p=np.array([.1,.2,.7]); s=rng.choice(3,10000,p=p)\nprint("observed frequencies",np.bincount(s,minlength=3)/len(s))''', '''import torch\ntorch.manual_seed(0); p=torch.tensor([.1,.2,.7]); s=torch.multinomial(p,10000,replacement=True); print(torch.bincount(s,minlength=3).float()/len(s))''', '''import numpy as np, matplotlib.pyplot as plt\np=np.array([.1,.2,.7]); plt.bar(["A","B","C"],p); plt.ylim(0,1); plt.title("Sampling distribution"); plt.ylabel("probability"); plt.show()''', '''p2=np.array([.1,.3,.6]); print("only probability changed:",p2,p2.sum())''', '''# Failure: probabilities do not sum to one\ntry: np.random.default_rng(0).choice(3,10,p=[.2,.2,.2])\nexcept ValueError as e: print("sampling failure:",e)'''),
'20': ('Neural network from scratch: forward -> loss -> backward -> update', '''import numpy as np\nx=np.arange(4.).reshape(-1,1); y=2*x+1; W=np.array([[.1]]); b=np.array([0.])\nyhat=x@W+b; L=((yhat-y)**2).mean(); d=2*(yhat-y)/len(x); dW=(x.T@d); db=d.sum()\nprint("forward",yhat.ravel(),"loss",L,"dW",dW,"db",db)\nW-=.1*dW; b-=.1*db; print("updated",W,b)''', '''import torch\nx=torch.arange(4.).unsqueeze(1); y=2*x+1; W=torch.tensor([[.1]],requires_grad=True); b=torch.tensor([0.],requires_grad=True)\nL=((x@W+b-y)**2).mean(); L.backward(); print(L.item(),W.grad,b.grad)''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.arange(4.); y=2*x+1; wvals=np.linspace(-1,3,100); losses=[np.mean((wvals[i]*x+0-y)**2) for i in range(100)]; plt.plot(wvals,losses); plt.xlabel("weight"); plt.ylabel("loss"); plt.title("Loss landscape of a tiny network"); plt.show()''', '''b2=np.array([.1]); print("only bias changed:",np.mean((x@W+b2-y)**2))''', '''# Failure: forget to divide the batch gradient by the number of examples\nprint("raw batch gradient magnitude is larger than mean gradient")'''),
'21': ('Automatic differentiation and the chain rule', '''import numpy as np\nf=lambda x:(x*x+1)**3; x=2.; h=1e-5\nanalytical=6*x*(x*x+1)**2; finite=(f(x+h)-f(x-h))/(2*h)\nprint("analytical",analytical,"finite",finite)''', '''import torch\nx=torch.tensor(2.,requires_grad=True); y=(x*x+1)**3; y.backward(); print("autograd",x.grad.item())''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.linspace(0,3,100); plt.plot(x,(x*x+1)**3); plt.scatter([2],[(2*2+1)**3]); plt.title("Function differentiated by autodiff"); plt.xlabel("x"); plt.ylabel("f(x)"); plt.show()''', '''h2=1e-3; print("only finite-difference step changed:",(f(x+h2)-f(x-h2))/(2*h2))''', '''# Failure: omit one chain-rule factor\nprint("wrong derivative:",3*(x*x+1)**2,"correct:",analytical)'''),
'22': ('Neural networks as function approximators', '''import numpy as np\nx=np.linspace(-3,3,7); print("x",x); print("target sin(x)",np.sin(x))''', '''import torch\nx=torch.linspace(-3,3,100).unsqueeze(1); y=torch.sin(x)\nn=torch.nn.Sequential(torch.nn.Linear(1,16),torch.nn.Tanh(),torch.nn.Linear(16,1)); opt=torch.optim.Adam(n.parameters(),lr=.03)\nfor _ in range(200):\n    opt.zero_grad(); L=((n(x)-y)**2).mean(); L.backward(); opt.step()\nprint("final MSE",L.item())''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.linspace(-3,3,200); plt.plot(x,np.sin(x),label="sin(x)"); plt.plot(x,np.sin(x),linestyle='--',label="ideal fit"); plt.legend(); plt.title("Function approximation target"); plt.show()''', '''width=8; print("change exactly one variable: hidden width",width)''', '''# Failure: a constant model cannot represent a changing function\nprint("constant-model MSE",np.mean((np.mean(np.sin(x))-np.sin(x))**2))'''),
'23': ('Invariance and equivariance under symmetry', '''import numpy as np\nx=np.array([1.,2.]); g=-x\nf=lambda z:(z*z).sum(); print("invariant:",f(x),f(g)); print("equivariant identity:",g)''', '''import torch\nx=torch.tensor([1.,2.]); g=-x; print((x*x).sum(),(g*g).sum())''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.array([1.,2.]); pts=np.array([x,-x]); plt.scatter(pts[:,0],pts[:,1]); plt.axis('equal'); plt.title("Symmetry: x and -x share squared norm"); plt.show()''', '''x2=np.array([1.,3.]); print("only second coordinate changed:",np.sum(x2*x2))''', '''# Failure: coordinate sum is not sign invariant\nprint("sum(x)",x.sum(),"sum(-x)",(-x).sum())'''),
'24': ('Graph neural networks: aggregate neighbor messages', '''import numpy as np\nA=np.array([[0.,1.,1.],[1.,0.,1.],[1.,1.,0.]])\nh=np.array([[1.],[2.],[4.]])\nprint("neighbor sums:\n",A@h); print("self+neighbors:\n",h+A@h)''', '''import torch\nA=torch.tensor([[0.,1.,1.],[1.,0.,1.],[1.,1.,0.]]); h=torch.tensor([[1.],[2.],[4.]])\nprint(A@h)''', '''import numpy as np, matplotlib.pyplot as plt\nA=np.array([[0,1,1],[1,0,1],[1,1,0]]); pos=np.array([[0,1],[1,-1],[-1,-1]])\nfor i,j in zip(*np.where(np.triu(A)==1)): plt.plot([pos[i,0],pos[j,0]],[pos[i,1],pos[j,1]])\nplt.scatter(pos[:,0],pos[:,1],s=200); plt.title("Three-node message-passing graph"); plt.axis('equal'); plt.show()''', '''h2=h.copy(); h2[0]=[10]; print("only node 1 changed:\n",A@h2)''', '''# Failure: ignore adjacency and average every node with every other node\nprint("global average",h.mean())'''),
'25': ('Generalization and held-out error', '''import numpy as np\nrng=np.random.default_rng(1); x=np.linspace(-1,1,40); y=x*x+.08*rng.normal(size=40); xt=np.linspace(-1,1,100); yt=xt*xt\nfor d in [1,3,15]:\n    c=np.polyfit(x,y,d); print("degree",d,"train",np.mean((np.polyval(c,x)-y)**2),"held-out",np.mean((np.polyval(c,xt)-yt)**2))''', '''import torch\nprint("Use the same principle in PyTorch: compare training loss with a separate held-out set.")''', '''import numpy as np, matplotlib.pyplot as plt\nrng=np.random.default_rng(1); x=np.linspace(-1,1,40); y=x*x+.08*rng.normal(size=40); xt=np.linspace(-1,1,100); yt=xt*xt\nfor d in [1,3,15]:\n c=np.polyfit(x,y,d); plt.plot(xt,np.polyval(c,xt),label=f"degree {d}")\nplt.scatter(x,y,s=12); plt.legend(); plt.title("Model complexity and generalization"); plt.show()''', '''d=5; c=np.polyfit(x,y,d); print("only polynomial degree changed to",d)''', '''# Failure: report training error as if it measured generalization\nprint("Training and test errors answer different questions.")'''),
'26': ('Scaling resources while controlling variables', '''import numpy as np\n# Controlled toy experiment: width is the only changed variable.\nx=np.linspace(-2,2,100); y=np.sin(x)\nfor width in [2,8,32]:\n    rng=np.random.default_rng(0); W1=rng.normal(size=(1,width)); W2=rng.normal(size=(width,1)); h=np.tanh(x[:,None]@W1); pred=h@W2; print(width,np.mean((pred-y[:,None])**2))''', '''import torch\nfor width in [2,8,32]:\n    torch.manual_seed(0); n=torch.nn.Sequential(torch.nn.Linear(1,width),torch.nn.Tanh(),torch.nn.Linear(width,1)); print(width,sum(p.numel() for p in n.parameters()))''', '''import numpy as np, matplotlib.pyplot as plt\nwidths=np.array([2,8,32,128]); params=widths+widths+1; plt.loglog(widths,params,marker='o'); plt.xlabel("width"); plt.ylabel("parameter count"); plt.title("One resource grows model size"); plt.show()''', '''width=16; print("only width changed:",width)''', '''# Failure: change width and learning rate together, making causality unclear\nprint("Confounded experiment: width and optimizer settings changed together.")'''),
'27': ('Representation learning: x -> z -> task', '''import numpy as np\nx=np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])\ny=np.array([0.,1.,1.,0.]); print("XOR inputs",x,"labels",y)''', '''import torch\nx=torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]]); y=torch.tensor([[0.],[1.],[1.],[0.]])\nn=torch.nn.Sequential(torch.nn.Linear(2,4),torch.nn.Tanh(),torch.nn.Linear(4,1)); opt=torch.optim.Adam(n.parameters(),lr=.05)\nfor _ in range(300):\n    opt.zero_grad(); L=((n(x)-y)**2).mean(); L.backward(); opt.step()\nprint("hidden representation:\n",n[0](x).detach())''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.array([[0,0],[0,1],[1,0],[1,1]]); y=np.array([0,1,1,0]); plt.scatter(x[:,0],x[:,1],c=y); plt.xlabel("x1"); plt.ylabel("x2"); plt.title("XOR is not linearly separable"); plt.show()''', '''print("change exactly one representation dimension")''', '''# Failure: remove the hidden layer; a single linear boundary cannot solve XOR\nprint("A linear model cannot represent XOR exactly.")'''),
'28': ('Contrastive learning: positives close, negatives far', '''import numpy as np\nz=np.array([[1.,0.],[.9,.1],[-1.,0.],[0.,1.]])\nsim=z@z.T; print(sim); print("positive similarity",sim[0,1],"negative",sim[0,2])''', '''import torch\nz=torch.tensor([[1.,0.],[.9,.1],[-1.,0.],[0.,1.]])\nsim=z@z.T; loss=(-torch.log_softmax(sim/.5,1).diag()).mean(); print(sim,loss.item())''', '''import numpy as np, matplotlib.pyplot as plt\nz=np.array([[1,0],[.9,.1],[-1,0],[0,1]]); plt.scatter(z[:,0],z[:,1]); plt.axis('equal'); plt.title("Embedding geometry for contrastive learning"); plt.show()''', '''z2=z.copy(); z2[1,0]=.8; print("only positive moved:",z2[0]@z2[1])''', '''# Failure: call dissimilar pairs positives\nprint("Wrong labels invert the learning signal.")'''),
'29': ('Conditional generation: p(x|c)', '''import numpy as np\nrng=np.random.default_rng(0)\nfor c,mu in [(0,-2),(1,2)]: print("condition",c,"samples",rng.normal(mu,.3,8))''', '''import torch\ntorch.manual_seed(0)\nfor mu in [-2.,2.]: print(torch.normal(torch.full((8,),mu),torch.full((8,),.3)))''', '''import numpy as np, matplotlib.pyplot as plt\nrng=np.random.default_rng(0); a=rng.normal(-2,.3,500); b=rng.normal(2,.3,500); plt.hist(a,bins=25,alpha=.6,label="c=0"); plt.hist(b,bins=25,alpha=.6,label="c=1"); plt.legend(); plt.title("Condition changes the generated distribution"); plt.show()''', '''mu=3.; print("only condition mean changed:",mu)''', '''# Failure: ignore the condition; both conditions become the same distribution\nprint("Condition dropped => no conditional control.")'''),
'30': ('Distribution shift and robustness', '''import numpy as np\nrng=np.random.default_rng(0); train=rng.normal(0,1,10000); shifted=rng.normal(2,1,10000)\nprint("train P(x>0)",np.mean(train>0)); print("shifted P(x>0)",np.mean(shifted>0))''', '''import torch\ntorch.manual_seed(0); a=torch.randn(10000); b=torch.randn(10000)+2; print((a>0).float().mean().item(),(b>0).float().mean().item())''', '''import numpy as np, matplotlib.pyplot as plt\nrng=np.random.default_rng(0); a=rng.normal(0,1,1000); b=rng.normal(2,1,1000); plt.hist(a,bins=30,alpha=.5,label="train"); plt.hist(b,bins=30,alpha=.5,label="shifted"); plt.legend(); plt.title("Train and shifted distributions"); plt.show()''', '''shift=1.; print("only shift magnitude changed:",shift)''', '''# Failure: assume test distribution is identical without checking it\nprint("Robustness requires measuring the deployment distribution.")'''),
'31': ('Transfer learning: reuse features, adapt a head', '''import numpy as np\nW=np.array([[1.,0.],[0.,1.],[1.,1.]])\nx=np.array([[1.,0.],[0.,1.]])\nfeatures=x@W.T; print(features)''', '''import torch\nbase=torch.nn.Linear(2,3); head=torch.nn.Linear(3,1); base.requires_grad_(False)\nx=torch.tensor([[1.,0.],[0.,1.]]); print(head(base(x)))''', '''import numpy as np, matplotlib.pyplot as plt\nfeatures=np.array([[1,0,1],[0,1,1]]); plt.imshow(features,aspect='auto'); plt.colorbar(); plt.title("Reused feature representation"); plt.xlabel("feature"); plt.ylabel("example"); plt.show()''', '''W2=W.copy(); W2[0,0]+=1; print("only one pretrained weight changed:\n",x@W2.T)''', '''# Failure: update the frozen base when the experiment is meant to freeze it\nprint("Frozen parameters must not receive optimizer updates.")'''),
'32': ('Empirical scaling law: metric ~ a * resource^b', '''import numpy as np\nr=np.array([1.,2.,4.,8.,16.]); loss=np.array([1.,.72,.55,.43,.35])\nb,a=np.polyfit(np.log(r),np.log(loss),1); print("exponent b=",b,"predicted loss at 32=",np.exp(a+b*np.log(32)))''', '''import torch\nr=torch.tensor([1.,2.,4.,8.,16.]); loss=torch.tensor([1.,.72,.55,.43,.35]); print(torch.polyfit(r,loss,1) if hasattr(torch,'polyfit') else "PyTorch can reproduce the log transform; fit with a standard optimizer.")''', '''import numpy as np, matplotlib.pyplot as plt\nr=np.array([1.,2.,4.,8.,16.]); loss=np.array([1.,.72,.55,.43,.35]); plt.loglog(r,loss,marker='o'); plt.xlabel("resource"); plt.ylabel("loss"); plt.title("Scaling trend on log-log axes"); plt.show()''', '''r2=32.; print("only resource changed for extrapolation:",r2)''', '''# Failure: extrapolate far outside observed resources as if the law were exact\nprint("Scaling laws are empirical trends, not guarantees.")'''),
'33': ('Inference temperature: softmax(logits/T)', '''import numpy as np\nlogits=np.array([2.,1.,.2,-1.])\nfor T in [.5,1.,2.]:\n    p=np.exp(logits/T); p/=p.sum(); print(T,p,"top",p.max())''', '''import torch\nlogits=torch.tensor([2.,1.,.2,-1.])\nfor T in [.5,1.,2.]: print(T,torch.softmax(logits/T,0))''', '''import numpy as np, matplotlib.pyplot as plt\nlogits=np.array([2.,1.,.2,-1.])\nfor T in [.5,1.,2.]:\n p=np.exp(logits/T); p/=p.sum(); plt.plot(p,marker='o',label=f"T={T}")\nplt.legend(); plt.xlabel("token"); plt.ylabel("probability"); plt.title("Temperature reshapes the distribution"); plt.show()''', '''T=1.5; print("only temperature changed:",T)''', '''# Failure: sample with negative temperature\ntry: print(np.exp(logits/-1))\nexcept Exception as e: print(e)'''),
'34': ('Deep-learning debugging as experimental science', '''import numpy as np\nx=np.array([1.,2.,3.]); y=2*x+1; w=0.; b=0.\nloss=lambda w,b:np.mean((w*x+b-y)**2)\nprint("initial loss",loss(w,b)); gw=(2*(w*x+b-y)*x).mean(); gb=(2*(w*x+b-y)).mean(); print("correct gradients",gw,gb)''', '''import torch\nx=torch.tensor([1.,2.,3.]); y=2*x+1; w=torch.tensor(0.,requires_grad=True); b=torch.tensor(0.,requires_grad=True); L=((w*x+b-y)**2).mean(); L.backward(); print(w.grad,b.grad)''', '''import numpy as np, matplotlib.pyplot as plt\nws=np.linspace(-1,3,100); plt.plot(ws,[np.mean((w*x-y)**2) for w in ws]); plt.title("A debugging symptom can be visible in the loss curve"); plt.xlabel("w"); plt.ylabel("loss"); plt.show()''', '''b2=.1; print("only bias changed:",loss(w,b2))''', '''# Failure: update in the wrong direction and observe loss increase\nw=0.; b=0.; eta=.1\nfor _ in range(5):\n e=w*x+b-y; w+=eta*(2*e*x).mean(); b+=eta*(2*e).mean(); print(loss(w,b))'''),
'35': ('Architectural bias: local convolution versus generic mapping', '''import numpy as np\nx=np.array([[0.,1.,0.,0.,0.],[0.,0.,1.,0.,0.],[0.,0.,0.,1.,0.],[0.,0.,0.,0.,0.],[0.,0.,0.,0.,0.]])\nk=np.array([[1.,0.,-1.],[1.,0.,-1.],[1.,0.,-1.]])\nprint("local response",(x[:3,:3]*k).sum())''', '''import torch\nx=torch.tensor([[[[0.,1.,0.,0.,0.],[0.,0.,1.,0.,0.],[0.,0.,0.,1.,0.],[0.,0.,0.,0.,0.],[0.,0.,0.,0.,0.]]]]); k=torch.tensor([[[[1.,0.,-1.],[1.,0.,-1.],[1.,0.,-1.]]]])\nprint(torch.nn.functional.conv2d(x,k))''', '''import numpy as np, matplotlib.pyplot as plt\nx=np.array([[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,0],[0,0,0,0,0]])\nplt.imshow(x); plt.colorbar(); plt.title("Spatial structure available to a convolution"); plt.show()''', '''k2=k.copy(); k2[0,0]=2; print("only one kernel entry changed:",(x[:3,:3]*k2).sum())''', '''# Failure: flatten the image and discard local neighborhoods before a local detector\nprint("Flattening destroys explicit spatial locality.")'''),
'36': ('Measuring representations with distance and similarity', '''import numpy as np\nz=np.array([[1.,0.],[.8,.2],[-1.,0.]])\nd=np.linalg.norm(z[:,None]-z[None,:],axis=-1); n=z/np.linalg.norm(z,axis=1,keepdims=True); c=n@n.T\nprint("distances:\n",d); print("cosine similarities:\n",c)''', '''import torch\nz=torch.tensor([[1.,0.],[.8,.2],[-1.,0.]])\nprint(torch.cdist(z,z)); n=torch.nn.functional.normalize(z,dim=1); print(n@n.T)''', '''import numpy as np, matplotlib.pyplot as plt\nz=np.array([[1,0],[.8,.2],[-1,0]]); plt.scatter(z[:,0],z[:,1]); plt.axis('equal'); plt.title("Representation geometry to measure"); plt.show()''', '''z2=z.copy(); z2[1,1]=.4; print("only one representation coordinate changed:\n",z2)''', '''# Failure: claim representation quality without a metric\nprint("Use distances, similarity, retrieval, or task metrics rather than visual guesses alone.")'''),
'37': ('Preference learning: policy probability gets an optimization signal', '''import numpy as np\np=np.array([.5,.5]); preferred=1; loss=-np.log(p[preferred]); print("loss",loss)\n# For a two-action softmax, increasing the preferred logit raises its probability.\nfor delta in [0,.5,1,2]:\n q=np.exp(np.array([0.,delta])); q/=q.sum(); print(delta,q,-np.log(q[1]))''', '''import torch\nlogits=torch.tensor([0.,0.],requires_grad=True); loss=-torch.log_softmax(logits,0)[1]; loss.backward(); print(torch.softmax(logits,0),logits.grad)''', '''import numpy as np, matplotlib.pyplot as plt\nd=np.linspace(-3,3,100); p=1/(1+np.exp(-d)); plt.plot(d,p); plt.xlabel("preferred-action logit advantage"); plt.ylabel("preferred probability"); plt.title("Preference signal changes policy probability"); plt.show()''', '''delta=.8; q=np.exp([0.,delta]); q/=q.sum(); print("only preference-logit advantage changed:",q)''', '''# Failure: optimize the probability of the rejected action instead\nq=np.exp([0.,1.]); q/=q.sum(); print("wrong preference direction gives preferred probability",q[1])''')
}

def cell(kind, source):
    if kind == 'markdown': return {'cell_type':'markdown','metadata':{},'source':source.splitlines(True)}
    return {'cell_type':'code','execution_count':None,'metadata':{},'outputs':[],'source':source.splitlines(True)}

def parse_sections(text):
    matches=list(re.finditer(r'^(#{1,3})\\s+(.+)$',text,re.M))
    sections=[]
    for i,m in enumerate(matches):
        end=matches[i+1].start() if i+1<len(matches) else len(text)
        sections.append((m.group(2).strip(),text[m.end():end].strip()))
    return sections

def exercise_headings(text):
    return [m.group(0).strip() for m in re.finditer(r'^#{1,4}\\s+.*(?:exercise|challenge|practice|try it|question).*$',text,re.I|re.M)]

def build_one(blog_path):
    n=blog_path.stem[:2]; title=blog_path.stem[3:].replace('-',' ').title(); text=blog_path.read_text(encoding='utf-8')
    if n not in RECIPES: return
    anchor,numpy_code,pytorch_code,viz_code,experiment_code,failure_code=RECIPES[n]
    cells=[cell('markdown',f'# {n} — {title}\\n\\n> **Notebook contract:** this is the complete interactive companion to `blogs/{blog_path.name}`. The Markdown blog is the source of truth; this notebook turns its theory and mathematics into executable learning.\\n\\n**Central computational anchor:** {anchor}')]
    for heading,body in parse_sections(text):
        cells.append(cell('markdown',f'## {heading}\\n\\n{body}'))
        low=heading.lower()
        if any(k in low for k in ['math','equation','calculation','derivative','gradient','forward','attention','convolution','example']):
            cells.append(cell('markdown','### Computational reconstruction\\n\\nFirst calculate the smallest numerical example by hand. Keep every intermediate product, sum, norm, probability, gradient, or update visible. Then run the identical numbers below.'))
            cells.append(cell('code',numpy_code))
    cells += [
        cell('markdown','## 🧮 Hand calculation\\n\\n**Do this before running code.** Write the blog example with concrete numbers, calculate every intermediate value, and predict the result. The next cell must reproduce exactly those numbers.'),
        cell('code',numpy_code),
        cell('markdown','## 🐍 NumPy — expose the mathematics\\n\\nNumPy is deliberately close to the equations. Inspect intermediate values rather than hiding the mathematics behind a high-level API.'),
        cell('code',numpy_code),
        cell('markdown','## 🔥 PyTorch — reproduce the same mathematics\\n\\nNow perform the same lesson calculation in PyTorch. Compare the result with NumPy before moving on.'),
        cell('code',pytorch_code),
        cell('markdown','## 📈 Visualization — answer a question\\n\\n**Question:** what changes in the mathematical object when the central variable in this lesson changes? The visualization below is tied to this chapter rather than being a generic chart.'),
        cell('code',viz_code),
        cell('markdown','## 🔬 Change exactly one variable\\n\\nKeep everything else fixed. Change only the named variable and explain why the output changed.'),
        cell('code',experiment_code),
        cell('markdown','## 💥 Intentional failure\\n\\nBreak the central computation in a way that is relevant to this lesson. Observe the symptom, explain its cause, and state the correct rule.'),
        cell('code',failure_code),
        cell('markdown','## 📝 Blog-synchronized exercises\\n\\nThese exercises are copied from the blog's exercise/challenge headings so the textbook and laboratory use the same learning tasks.'),
    ]
    ex=exercise_headings(text)
    if ex:
        for i,h in enumerate(ex,1): cells.append(cell('markdown',f'### BLOG-{n}-EX-{i:02d}\\n\\n{h}\\n\\n**Notebook task:** solve this using the concepts and numerical anchor above; show your work before coding.'))
    else:
        cells.append(cell('markdown',f'### BLOG-{n}-EX-01\\n\\nNo explicit exercise heading was detected in the blog. Create a new numerical example using the chapter anchor without introducing a new concept.'))
    cells += [
        cell('markdown','## 🚀 Mini-project\\n\\nBuild a slightly larger version of the exact idea from this blog. Keep the same mathematical principle, make the data concrete, visualize the result, and explain one failure mode. Do not jump to an unrelated application.'),
        cell('markdown','## 🔬 Advanced research bridge\\n\\nConnect this chapter to a modern research question. Identify the assumption made by the simple experiment, find one way real systems relax that assumption, and propose a small reproducible experiment. Clearly separate what the blog established from your hypothesis.'),
        cell('markdown','## 🎯 Mastery check\\n\\n1. Explain the central idea without code.\\n2. Recalculate the numerical anchor by hand.\\n3. Explain what each important symbol means.\\n4. Predict what happens when the controlled variable changes.\\n5. Explain the intentional failure.\\n6. Reproduce the result with NumPy and PyTorch.\\n7. State one research-level question this lesson naturally leads to.')
    ]
    nb={'cells':cells,'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':'3.11'},'blog_source':blog_path.name,'curriculum_contract':'Blog is source of truth; notebook is complete interactive computational companion.'},'nbformat':4,'nbformat_minor':5}
    out=NOTEBOOKS/(blog_path.stem+'.ipynb'); out.write_text(json.dumps(nb,ensure_ascii=False,indent=1),encoding='utf-8')

def main():
    NOTEBOOKS.mkdir(exist_ok=True)
    blogs=sorted(p for p in BLOGS.glob('[0-9][0-9]-*.md') if 1 <= int(p.name[:2]) <= 37)
    if len(blogs)!=37: raise SystemExit(f'Expected 37 curriculum blogs, found {len(blogs)}')
    for p in blogs: build_one(p)
    print(f'Rebuilt {len(blogs)} complete blog-as-notebook lessons.')

if __name__=='__main__': main()
