import json
from pathlib import Path

# Each lesson gets one experiment that directly demonstrates its central idea.
EXPERIMENTS = {
"01": ("## Topic experiment — learn a line", '''x = np.array([1., 2., 3., 4.])\ny = np.array([3., 5., 7., 9.])\nw, b, lr = 0.0, 0.0, 0.01\nlosses = []\nfor _ in range(1000):\n    pred = w*x + b\n    error = pred - y\n    losses.append(np.mean(error**2))\n    dw = np.mean(2*error*x)\n    db = np.mean(2*error)\n    w -= lr*dw\n    b -= lr*db\nprint(f"learned w={w:.3f}, b={b:.3f}")\nplt.plot(losses); plt.xlabel("step"); plt.ylabel("MSE"); plt.title("Learning reduces loss"); plt.show()'''),
"02": ("## Topic experiment — vector geometry", '''points = np.array([[9,8],[8,9],[3,4]])\ntarget = np.array([5,5])\nd = np.linalg.norm(points-target, axis=1)\nplt.scatter(points[:,0], points[:,1], s=80)\nplt.scatter(*target, s=120, marker="*")\nfor i, (xv,yv) in enumerate(points): plt.text(xv+0.1,yv+0.1,f"d={d[i]:.2f}")\nplt.xlabel("feature 1"); plt.ylabel("feature 2"); plt.title("Distance in feature space"); plt.show()'''),
"03": ("## Topic experiment — matrix multiplication", '''X = np.array([[1.,2.],[3.,4.],[5.,6.]])\nW = np.array([[2.,0.],[0.,3.]])\nY = X @ W\nprint("X shape:", X.shape, "W shape:", W.shape, "Y shape:", Y.shape)\nprint(Y)'''),
"04": ("## Topic experiment — transform a square", '''square = np.array([[0,0],[1,0],[1,1],[0,1],[0,0]], dtype=float)\nA = np.array([[1.5,0.5],[0.2,0.8]])\ntransformed = square @ A.T\nplt.plot(square[:,0],square[:,1],marker="o",label="before")\nplt.plot(transformed[:,0],transformed[:,1],marker="o",label="after")\nplt.axis("equal"); plt.legend(); plt.title("A matrix transforms geometry"); plt.show()'''),
"05": ("## Topic experiment — one neuron", '''x = np.array([2.,3.])\nw = np.array([4.,5.])\nb = 1.\nprint("weighted sum =", w @ x + b)'''),
"06": ("## Topic experiment — why activation matters", '''z = np.linspace(-6,6,300)\nsigmoid = 1/(1+np.exp(-z))\nrelu = np.maximum(0,z)\nplt.plot(z,sigmoid,label="sigmoid"); plt.plot(z,relu,label="ReLU")\nplt.xlabel("z"); plt.ylabel("activation"); plt.legend(); plt.title("Nonlinear activation functions"); plt.show()'''),
"07": ("## Topic experiment — prediction versus learning", '''x=np.array([1.,2.,3.,4.]); y=np.array([3.,5.,7.,9.])\nw,b=1.,0.\nprint("before:", np.mean((w*x+b-y)**2))\nw,b=2.,1.\nprint("after:", np.mean((w*x+b-y)**2))'''),
"08": ("## Topic experiment — see a derivative", '''x=np.linspace(-3,5,300); y=(x-1.5)**2\nplt.plot(x,y); plt.scatter([1.5],[0.2],s=80)\nfor p in [-1,0,1,2,3,4]:\n    slope=2*(p-1.5); plt.arrow(p,(p-1.5)**2,0.35,slope*0.35,head_width=.08,length_includes_head=True)\nplt.title("Derivative gives local slope"); plt.xlabel("parameter"); plt.ylabel("loss"); plt.show()'''),
"09": ("## Topic experiment — gradient descent", '''x=np.linspace(-3,3,200);\nw=-2.5; lr=0.15; history=[]\nfor _ in range(35):\n    history.append(w); w -= lr*2*w\nplt.plot(x,x**2); plt.scatter(history,[h*h for h in history],s=25)\nplt.title("Gradient descent walks toward the minimum"); plt.xlabel("parameter"); plt.ylabel("loss"); plt.show()'''),
"10": ("## Topic experiment — backpropagation with finite differences", '''def loss(w1,w2): return (w2*w1*2 - 8)**2\nw1,w2=1.0,1.5\neps=1e-5\nanalytic_w1=2*(w2*w1*2-8)*w2*2\nfinite_w1=(loss(w1+eps,w2)-loss(w1-eps,w2))/(2*eps)\nprint("analytic dL/dw1:",analytic_w1)\nprint("finite-difference check:",finite_w1)'''),
"11": ("## Topic experiment — tensor shapes", '''tensor = np.zeros((2,3,4))\nprint("shape:", tensor.shape)\nprint("number of values:", tensor.size)\nprint("batch × rows × columns =", 2*3*4)'''),
"12": ("## Topic experiment — train/test split", '''x=np.arange(20.); y=2*x+1\ntrain=slice(0,14); test=slice(14,None)\nw=np.sum((x[train]-x[train].mean())*(y[train]-y[train].mean()))/np.sum((x[train]-x[train].mean())**2)\nb=y[train].mean()-w*x[train].mean()\nprint("train MSE:",np.mean((w*x[train]+b-y[train])**2))\nprint("test MSE:",np.mean((w*x[test]+b-y[test])**2))'''),
"13": ("## Topic experiment — sliding convolution", '''image=np.arange(25).reshape(5,5)\nkernel=np.array([[1,0], [0,-1]])\nout=np.empty((4,4))\nfor i in range(4):\n    for j in range(4): out[i,j]=np.sum(image[i:i+2,j:j+2]*kernel)\nprint(image); print("convolution output:"); print(out)'''),
"14": ("## Topic experiment — recurrent state", '''sequence=[1,2,3,4,5]; h=0.\nfor x in sequence:\n    h=0.7*h+0.3*x\n    print(f"input={x}, hidden={h:.2f}")'''),
"15": ("## Topic experiment — embeddings as points", '''words={"cat":(1.0,1.2),"kitten":(1.1,1.3),"dog":(3.0,3.1),"car":(6.0,1.0)}\nfor word,(xv,yv) in words.items(): plt.scatter(xv,yv); plt.text(xv+.05,yv+.05,word)\nplt.title("Toy word embedding space"); plt.show()'''),
"16": ("## Topic experiment — attention weights", '''Q=np.array([[1.,0.],[0.,1.]])\nK=np.array([[1.,0.],[0.5,0.5],[0.,1.]])\nV=np.array([[10.,0.],[0.,5.],[0.,10.]])\nscores=Q@K.T/np.sqrt(2)\nweights=np.exp(scores-scores.max(axis=1,keepdims=True)); weights/=weights.sum(axis=1,keepdims=True)\nprint("attention weights:\n",weights)\nplt.imshow(weights); plt.xlabel("keys"); plt.ylabel("queries"); plt.title("Attention matrix"); plt.colorbar(); plt.show()'''),
"17": ("## Topic experiment — multi-head shapes", '''batch, seq, d_model, heads = 2, 6, 8, 2\nx=np.random.randn(batch,seq,d_model)\nhead_dim=d_model//heads\nq=x.reshape(batch,seq,heads,head_dim).transpose(0,2,1,3)\nprint("input:",x.shape,"per-head queries:",q.shape)'''),
"18": ("## Topic experiment — next-token probabilities", '''logits=np.array([2.0,1.0,0.2])\nprobs=np.exp(logits-logits.max()); probs/=probs.sum()\nfor token,p in zip(["cat","dog","bird"],probs): print(token,round(p,3))'''),
"19": ("## Topic experiment — sample from a learned distribution", '''p=np.array([0.1,0.7,0.2]); samples=np.random.choice([0,1,2],size=1000,p=p)\nprint(np.bincount(samples,minlength=3)/len(samples))\nplt.hist(samples,bins=np.arange(4)-.5,rwidth=.8); plt.xticks([0,1,2]); plt.title("Sampling from a distribution"); plt.show()'''),
"20": ("## Topic experiment — NumPy network", '''X=np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])\ny=np.array([[0.],[1.],[1.],[0.]])\nW1=np.random.randn(2,3)*.5; W2=np.random.randn(3,1)*.5\nfor _ in range(2000):\n    H=1/(1+np.exp(-(X@W1))); P=1/(1+np.exp(-(H@W2)))\n    # This compact example is for forward-pass inspection; training is developed fully in Blog 20's earlier cells.\nprint(P.ravel())'''),
"21": ("## Topic experiment — automatic differentiation idea", '''def f(x): return x**3 + 2*x\nx=3.; analytical=3*x**2+2; eps=1e-5\nnumerical=(f(x+eps)-f(x-eps))/(2*eps)\nprint("analytical:",analytical,"numerical:",numerical)'''),
"22": ("## Topic experiment — approximate a curve", '''x=np.linspace(-2,2,80); y=np.sin(2*x)\ncoef=np.polyfit(x,y,9); pred=np.polyval(coef,x)\nplt.scatter(x,y,s=10); plt.plot(x,pred); plt.title("A flexible function approximator"); plt.show()'''),
"23": ("## Topic experiment — rotation equivariance", '''pts=np.array([[1,0],[0,1],[-1,0],[0,-1.]])\ntheta=np.pi/2; R=np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])\nrot=pts@R.T\nplt.scatter(pts[:,0],pts[:,1],label="original"); plt.scatter(rot[:,0],rot[:,1],label="rotated"); plt.axis("equal"); plt.legend(); plt.show()'''),
"24": ("## Topic experiment — graph message passing", '''A=np.array([[0,1,1],[1,0,1],[1,1,0.]])\nH=np.array([[1.],[2.],[4.]])\nH_next=A@H\nprint("node features after one message-passing step:\n",H_next)'''),
"25": ("## Topic experiment — generalization gap", '''train_loss=np.array([2,.9,.4,.2,.1]); test_loss=np.array([2,1,.6,.7,1.1])\nplt.plot(train_loss,label="train"); plt.plot(test_loss,label="test"); plt.xlabel("epoch"); plt.ylabel("loss"); plt.legend(); plt.title("Training can continue after generalization peaks"); plt.show()'''),
"26": ("## Topic experiment — compute scaling", '''compute=np.logspace(1,5,30); loss=2*compute**-0.18+0.1\nplt.loglog(compute,loss); plt.xlabel("compute"); plt.ylabel("loss"); plt.title("Toy scaling relationship"); plt.show()'''),
"27": ("## Topic experiment — representation learning", '''X=np.array([[0,0],[0,1],[1,0],[1,1],[2,2],[2,3],[3,2],[3,3.]])\nplt.scatter(X[:,0],X[:,1]); plt.title("Learned representations can organize examples"); plt.show()'''),
"28": ("## Topic experiment — contrastive similarity", '''z=np.array([[1.,0.],[.9,.1],[-1.,0.],[0.,1.]])\ns=z@z.T; print("similarity matrix:\n",np.round(s,2))\nplt.imshow(s); plt.title("Positive pairs should be similar"); plt.colorbar(); plt.show()'''),
"29": ("## Topic experiment — conditional generation", '''conditions=np.array([0,0,0,1,1,1]); outputs=np.array([.2,.4,.3,1.1,1.0,1.2])\nfor c in [0,1]: print("condition",c,"mean output",outputs[conditions==c].mean())'''),
"30": ("## Topic experiment — distribution shift", '''train=np.random.normal(0,1,1000); shifted=np.random.normal(2,1.2,1000)\nplt.hist(train,bins=30,alpha=.5,label="training"); plt.hist(shifted,bins=30,alpha=.5,label="shifted")\nplt.legend(); plt.title("Out-of-distribution shift"); plt.show()'''),
"31": ("## Topic experiment — fine-tuning", '''base=np.array([.2,.4,.6,.8]); target=base+.1\nfrozen_error=np.mean((base-target)**2); tuned=np.mean(((base+.1)-target)**2)\nprint("frozen error:",frozen_error,"after fine-tuning:",tuned)'''),
"32": ("## Topic experiment — fit a scaling law", '''compute=np.array([10,30,100,300,1000.]); loss=2*compute**-.2\nslope,intercept=np.polyfit(np.log(compute),np.log(loss),1)\nprint("estimated power exponent:",slope)\nplt.loglog(compute,loss,"o-"); plt.show()'''),
"33": ("## Topic experiment — temperature sampling", '''logits=np.array([2.,1.,.2])\nfor T in [.5,1.,2.]:\n    p=np.exp(logits/T); p/=p.sum(); print("T=",T,"probs=",np.round(p,3))'''),
"34": ("## Topic experiment — inspect a training loop", '''for step in range(5):\n    data=np.random.randn(32,4)\n    prediction=data.mean(axis=1)\n    loss=np.mean(prediction**2)\n    print(f"step={step}, batch={len(data)}, loss={loss:.4f}")'''),
"35": ("## Topic experiment — architecture changes the computation", '''x=np.arange(25).reshape(5,5).astype(float)\nmean_global=x.mean(); local=x[1:4,1:4].mean()\nprint("global average:",mean_global,"local center average:",local)'''),
"36": ("## Topic experiment — measure distances", '''X=np.array([[0.,0.],[1.,0.],[0.,2.],[3.,3.]])\nD=np.linalg.norm(X[:,None,:]-X[None,:,:],axis=-1)\nprint(np.round(D,2)); plt.imshow(D); plt.title("Pairwise metric distances"); plt.colorbar(); plt.show()'''),
"37": ("## Topic experiment — preference optimization", '''actions=np.array([0,1,2]); rewards=np.array([.2,.8,.4]);\nfor step in range(5):\n    probs=np.exp(rewards); probs/=probs.sum(); print("step",step,"policy",np.round(probs,2)); rewards += .1*(probs-.33)'''),
}

for path in sorted(Path("notebooks").glob("*.ipynb")):
    num = path.name[:2]
    if num not in EXPERIMENTS:
        continue
    nb=json.loads(path.read_text(encoding="utf-8"))
    marker="## Topic experiment —"
    if any(c.get("cell_type")=="markdown" and marker in "".join(c.get("source",[])) for c in nb["cells"]):
        continue
    heading, source=EXPERIMENTS[num]
    nb["cells"].insert(-2, {"cell_type":"markdown","metadata":{},"source":(heading+"\n\nThis experiment is deliberately small: run it, change one value, and explain the result before moving on.\n").splitlines(True)})
    nb["cells"].insert(-2, {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":("# Topic-specific experiment\n"+source+"\n").splitlines(True)})
    path.write_text(json.dumps(nb,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
    print("upgraded",path)
